export const data = {
  entrada: {
    circuito: "",
    desc: "",
    potencia: 1,
    unidades: "",
    factor: 1,
    fases: 1,
    voltaje: 120,
    distancia: 1,
  },
  personalizado: false,
  AG: false,
  numerico: ["potencia", "factor", "fases", "voltaje", "distancia", "area"],
  minimos: {
    AG: 1500,
    PA: 1500,
    LP: 1500,
    vivienda: 32,
    hospital: 22,
    induComercio: 22,
    colegio: 32,
  },
  rows: [],
};
